---
galaxy_info:
  role_name: wazuh_agent
  description: CompanyXYZ-NG wazuh_agent role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
