---
galaxy_info:
  author: CompanyXYZ-NG
  role_name: radius_secure
  description: CompanyXYZ-NG radius_secure role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
