---
common_hardening_ssh_client_alive_interval: 300
common_hardening_ssh_client_alive_count_max: 0
common_hardening_ssh_permit_root_login: "no"
common_hardening_login_banner: >-
  Authorized access only. Activity is logged and monitored.
