---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^docker/authentik/blueprints/

  - repo: local
    hooks:
      - id: authentik-blueprint-yaml-syntax
        name: Authentik Blueprint YAML syntax
        entry: python scripts/check_yaml_syntax.py
        language: system
        files: ^docker/authentik/blueprints/.*\.ya?ml$

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.6.1
    hooks:
      - id: ansible-lint
        files: ^ansible/

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
