[program:sshd]
command=/usr/sbin/sshd -D -e
autorestart=true
priority=10

[program:dnsmasq]
command=/usr/sbin/dnsmasq --keep-in-foreground --log-facility=- --address=/server1.companyxyz.lab/172.16.50.1
autorestart=true
priority=20

[program:freeradius]
command=/usr/sbin/freeradius -f -l stdout
autorestart=true
priority=30

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
priority=50
