---
galaxy_info:
  role_name: suricata
  description: CompanyXYZ-NG suricata role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
