global(
  DefaultNetstreamDriver="gtls"
  DefaultNetstreamDriverCAFile="/run/certs/ca.crt"
  DefaultNetstreamDriverCertFile="/run/certs/relay.crt"
  DefaultNetstreamDriverKeyFile="/run/certs/relay.key"
)

module(load="imtcp")
input(
  type="imtcp"
  port="6514"
  StreamDriver.Name="gtls"
  StreamDriver.Mode="1"
  StreamDriver.AuthMode="x509/name"
  PermittedPeer=[
    "server1.companyxyz.lab",
    "edge.companyxyz.lab",
    "core.companyxyz.lab",
    "dist1.companyxyz.lab",
    "dist2.companyxyz.lab",
    "fw-core.companyxyz.lab",
    "fw-dmz.companyxyz.lab"
  ]
)

template(name="CxyzRemote" type="string" string="%timereported:::date-rfc3339% %hostname% %syslogtag%%msg%\n")
*.* action(type="omfile" file="/var/log/cxyz/remote.log" template="CxyzRemote")
