---
galaxy_info:
  role_name: frr_fabric
  author: nguyan
  description: CompanyXYZ-NG frr_fabric role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
