---
galaxy_info:
  role_name: ntp_secure
  author: nguyan
  description: CompanyXYZ-NG ntp_secure role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
