#!/usr/bin/env python3
"""Fail closed when local Wazuh PKI no longer matches reviewed service identities."""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CERTS = ROOT / "docker/wazuh/certs"
CA = CERTS / "root-ca.pem"

IDENTITIES = {
    "wazuh-indexer.pem": "wazuh-indexer",
    "wazuh.manager.pem": "wazuh.manager",
    "wazuh.dashboard.pem": "wazuh.dashboard",
}
REQUIRED = {
    "root-ca.pem",
    "root-ca-manager.pem",
    "admin.pem",
    "admin-key.pem",
    "wazuh-indexer.pem",
    "wazuh-indexer-key.pem",
    "wazuh.manager.pem",
    "wazuh.manager-key.pem",
    "wazuh.dashboard.pem",
    "wazuh.dashboard-key.pem",
}


def run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, capture_output=True, text=True, check=False, timeout=15)


def has_days(path: pathlib.Path, days: int) -> bool:
    result = run("openssl", "x509", "-checkend", str(days * 86400), "-noout", "-in", str(path))
    return result.returncode == 0


def dns_sans(path: pathlib.Path) -> set[str]:
    result = run("openssl", "x509", "-in", str(path), "-noout", "-ext", "subjectAltName")
    if result.returncode != 0:
        return set()
    return set(re.findall(r"DNS:([^,\s]+)", result.stdout))


def verifies(path: pathlib.Path) -> bool:
    return run("openssl", "verify", "-CAfile", str(CA), str(path)).returncode == 0


def main() -> int:
    if not CERTS.is_dir():
        print("Wazuh PKI directory is missing; run make wazuh-config", file=sys.stderr)
        return 1
    missing = sorted(name for name in REQUIRED if not (CERTS / name).is_file())
    if missing:
        print(
            "Wazuh PKI is missing reviewed identity files: " + ", ".join(missing),
            file=sys.stderr,
        )
        print(
            "If this directory was generated by an older revision, rotate/reissue it using docs/PKI-ROTATION.md; "
            "do not disable hostname verification.",
            file=sys.stderr,
        )
        return 1
    if not has_days(CA, 90):
        print("Wazuh root CA expires within 90 days; perform planned PKI rotation", file=sys.stderr)
        return 1

    errors: list[str] = []
    for filename, dns_name in IDENTITIES.items():
        cert = CERTS / filename
        if not has_days(cert, 30):
            errors.append(f"{filename} expires within 30 days")
        if dns_name not in dns_sans(cert):
            errors.append(f"{filename} is missing DNS SAN {dns_name}")
        if not verifies(cert):
            errors.append(f"{filename} does not verify against root-ca.pem")
    if errors:
        print("Wazuh PKI identity validation failed:", file=sys.stderr)
        for error in errors:
            print(f" - {error}", file=sys.stderr)
        print("Follow docs/PKI-ROTATION.md and re-run make wazuh-config.", file=sys.stderr)
        return 1
    print("OK: Wazuh PKI chain, expiry and service DNS identities are valid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
