#!/usr/bin/env python3
"""Render the Path B Ansible inventory from canonical fabric intent."""

from __future__ import annotations

import argparse
import pathlib
import sys

import yaml


ROOT = pathlib.Path(__file__).resolve().parent.parent
INTENT = ROOT / "intent" / "fabric.yaml"
OUTPUT = ROOT / "ansible" / "inventory" / "vm-fabric.yml"


class Dumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def hosts(nodes: dict, names: list[str]) -> dict:
    return {name: {"ansible_host": nodes[name]["mgmt_ip"]} for name in names}


def render(intent: dict) -> str:
    nodes = intent["nodes"]
    vyos_routers = [name for name, node in nodes.items() if node["role"] in {"router", "isp"}]
    vyos_firewalls = [name for name, node in nodes.items() if node["role"] == "firewall"]
    linux = [name for name, node in nodes.items() if node["role"] == "endpoint"]
    clients = [name for name in linux if name.startswith("pc")]
    servers = [name for name in linux if name == "server1"]
    dmz_hosts = [name for name in linux if name not in {*clients, *servers}]
    inventory = {
        "all": {
            "children": {
                "network_devices": {
                    "children": {
                        "vyos_routers": {
                            "vars": {
                                "ansible_connection": "ansible.netcommon.network_cli",
                                "ansible_network_os": "vyos.vyos.vyos",
                                "ansible_user": "vyos",
                            },
                            "hosts": hosts(nodes, vyos_routers),
                        },
                        "vyos_firewalls": {
                            "vars": {
                                "ansible_connection": "ansible.netcommon.network_cli",
                                "ansible_network_os": "vyos.vyos.vyos",
                                "ansible_user": "vyos",
                            },
                            "hosts": hosts(nodes, vyos_firewalls),
                        },
                    }
                },
                "linux_nodes": {
                    "vars": {"ansible_connection": "ssh", "ansible_user": "ansible"},
                    "children": {
                        "clients": {"hosts": hosts(nodes, clients)},
                        "servers": {"hosts": hosts(nodes, servers)},
                        "dmz_hosts": {"hosts": hosts(nodes, dmz_hosts)},
                    },
                },
            }
        }
    }
    header = (
        "# GENERATED by scripts/render_vm_inventory.py from intent/fabric.yaml.\n"
        "# Verify SSH host keys into inventory/known_hosts before vm-configure.\n"
        "---\n"
    )
    return header + yaml.dump(inventory, Dumper=Dumper, sort_keys=False)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(yaml.safe_load(INTENT.read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            print("ansible/inventory/vm-fabric.yml is stale; run python scripts/render_vm_inventory.py", file=sys.stderr)
            return 1
        print("OK: Path B inventory matches canonical fabric intent")
        return 0
    OUTPUT.write_text(rendered)
    print(f"rendered {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
