#!/usr/bin/env python3
"""Render cluster-specific Path C policy without widening static egress.

Traefik must watch Kubernetes CRDs, so it needs TCP/443 to the API Service.
The Service ClusterIP is cluster-specific.  Rather than committing a broad
"443 anywhere" NetworkPolicy exception, resolve that IP at deploy time and
write an ignored /32 policy.
"""
from __future__ import annotations

import argparse
import ipaddress
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "k8s/runtime-networkpolicy.yaml"


def cluster_ip() -> str:
    result = subprocess.run(
        ["kubectl", "-n", "default", "get", "service", "kubernetes", "-o", "jsonpath={.spec.clusterIP}"],
        capture_output=True,
        text=True,
        check=False,
        timeout=15,
    )
    value = result.stdout.strip()
    if result.returncode != 0 or not value:
        raise RuntimeError(f"cannot resolve kubernetes.default ClusterIP: {result.stderr.strip()}")
    addr = ipaddress.ip_address(value)
    if addr.version != 4:
        raise RuntimeError(f"Path C runtime policy currently requires an IPv4 API Service, got {value}")
    return value


def rendered(api_ip: str) -> str:
    return f"""# GENERATED by scripts/render_k8s_runtime_policy.py; DO NOT COMMIT.\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: traefik-kubernetes-api\n  namespace: cxyz-security\nspec:\n  podSelector:\n    matchLabels:\n      app: traefik\n  policyTypes: [Egress]\n  egress:\n    - to:\n        - ipBlock:\n            cidr: {api_ip}/32\n      ports:\n        - protocol: TCP\n          port: 443\n"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate an existing runtime policy against this cluster")
    args = parser.parse_args()
    try:
        api_ip = cluster_ip()
    except (RuntimeError, ValueError) as exc:
        print(f"runtime NetworkPolicy: {exc}", file=sys.stderr)
        return 1
    expected = rendered(api_ip)
    if args.check:
        if not DEST.exists() or DEST.read_text() != expected:
            print(f"{DEST.relative_to(ROOT)} is missing/stale for API ClusterIP {api_ip}", file=sys.stderr)
            return 1
        print(f"OK: runtime Traefik API policy is pinned to {api_ip}/32")
        return 0
    DEST.write_text(expected)
    print(f"rendered {DEST.relative_to(ROOT)} for kubernetes.default={api_ip}/32")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
