#!/usr/bin/env python3
"""Render cluster-specific Traefik -> Kubernetes API egress policy.

NetworkPolicy implementations can observe Service traffic either before or
after kube-proxy/CNI DNAT.  To avoid depending on one CNI's ordering, permit
TCP/443 to both the kubernetes.default ClusterIP and the concrete API endpoint
addresses discovered from the Endpoints object.  Everything else remains under
the namespace default-deny policy.
"""
from __future__ import annotations

import argparse
import ipaddress
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "k8s/runtime-networkpolicy.yaml"


def kubectl_value(*args: str) -> str:
    result = subprocess.run(
        ["kubectl", *args], capture_output=True, text=True, check=False, timeout=15
    )
    value = result.stdout.strip()
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"kubectl {' '.join(args)} failed")
    return value


def api_destinations() -> list[str]:
    service_ip = kubectl_value(
        "-n", "default", "get", "service", "kubernetes", "-o", "jsonpath={.spec.clusterIP}"
    )
    endpoint_text = kubectl_value(
        "-n", "default", "get", "endpoints", "kubernetes", "-o", "jsonpath={.subsets[*].addresses[*].ip}"
    )
    candidates = [service_ip, *endpoint_text.split()]
    addresses: set[str] = set()
    for value in candidates:
        if not value:
            continue
        addr = ipaddress.ip_address(value)
        if addr.version != 4:
            raise RuntimeError(f"Path C runtime policy currently requires IPv4 API destinations, got {value}")
        addresses.add(str(addr))
    if not addresses:
        raise RuntimeError("kubernetes.default has no ClusterIP/API endpoint addresses")
    return sorted(addresses, key=ipaddress.ip_address)


def rendered(api_ips: list[str]) -> str:
    destinations = "\n".join(
        f"        - ipBlock:\n            cidr: {api_ip}/32" for api_ip in api_ips
    )
    return f"""# GENERATED by scripts/render_k8s_runtime_policy.py; DO NOT COMMIT.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traefik-kubernetes-api
  namespace: cxyz-security
spec:
  podSelector:
    matchLabels:
      app: traefik
  policyTypes: [Egress]
  egress:
    - to:
{destinations}
      ports:
        - protocol: TCP
          port: 443
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate an existing runtime policy against this cluster")
    args = parser.parse_args()
    try:
        api_ips = api_destinations()
    except (RuntimeError, ValueError) as exc:
        print(f"runtime NetworkPolicy: {exc}", file=sys.stderr)
        return 1
    expected = rendered(api_ips)
    if args.check:
        if not DEST.exists() or DEST.read_text() != expected:
            print(
                f"{DEST.relative_to(ROOT)} is missing/stale for API destinations {', '.join(api_ips)}",
                file=sys.stderr,
            )
            return 1
        print(f"OK: runtime Traefik API policy permits only TCP/443 to {', '.join(api_ips)}")
        return 0
    DEST.write_text(expected)
    print(f"rendered {DEST.relative_to(ROOT)} for kubernetes API destinations {', '.join(api_ips)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
