---
galaxy_info:
  role_name: syslog_tls
  description: CompanyXYZ-NG syslog_tls role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
