! vEOS-Dis-I -> FRR. VRRP master (priority 150) for user gateway .254
frr defaults traditional
hostname dist1
password zebra
!
interface eth2
 ip address 192.168.10.252/24
 vrrp 10 ip 192.168.10.254
 vrrp 10 priority 150
!
line vty
