! vEOS-Dis-II -> FRR. VRRP backup (priority 100)
frr defaults traditional
hostname dist2
password zebra
!
interface eth2
 ip address 192.168.40.252/24
 vrrp 10 ip 192.168.40.254
 vrrp 10 priority 100
!
line vty
