---
galaxy_info:
  role_name: common_hardening
  description: CompanyXYZ-NG common_hardening role
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble]
dependencies: []
